### ISSUE TITLE
How to check the login information

### ISSUE THREAD

**Issue by hem-raj** [dsoares/roundcube-geolocation#1]
Hello Mam / Sir,

I have installed this plugin. But how I can check the users login information generated by this plugin.

Regards,
Hem Singh

**Comment by dsoares** [comment]
Hello,

I'm sorry for the very late answer, i've just replied to your email explaining this and I added some more information to the README.

**Comment by mckaygerhard** [comment]
hello @dsoares i wish too this info how to use, due i reworked the converse.js plugin so..

as i suspech like you, you have used plugins in roundcube for intranet's right? me too need intranet capabilities, so in converse.js i have the idea to track the ip and location in resource identifier, using the provided functionallity by your plugin..

how can i use the ip and location provided by your plugin? in other plugin!?

**Comment by dsoares** [comment]
If you want to use the geolocation features in another plugin, you may do something like:

``` php
$this->require_plugin('geolocation');
$geo = geolocation::get_instance()->get_geolocation($ip);
```

It returns an `array('city' => '...', 'region' => '...', 'country' => '...')` which you may use.

**Comment by tyronelucero** [comment]
great! really easy to use it!

**Comment by mckaygerhard** [comment]
Oh thanks, really easy! i made a feature into converse.js and made public in gitlab later

PD: umm how can i detect if plugin require (by example not have) fail?

**Comment by dsoares** [comment]
Check `load_plugin()` in `program/lib/Roundcube/rcube_plugin_api.php`.
It throws/raises an error if it can not load the plugin. Use try/catch.

**Comment by mckaygerhard** [comment]
thanks, that's all i need!
