### ISSUE TITLE
Issue with geolocation_internal_networks

### ISSUE THREAD

**Issue by CRtEurope** [dsoares/roundcube-geolocation#2]
There is an issue with geolocation_internal_networks. When I add several IP's (IPv4 or IPv6) with different descriptions then only the first description is recognized in the line 16.

Example:  
    '2001:470:6d:80:e46e:7b8f:83a9:f718'      => 'Something 1',
    '2001:470:6d:80:224:1dff:fe84:798'       => 'Something 2',
    '2001:470:6d:80:a5f6:5a97:a53:71c8'  => 'Something 3',
    '2001:470:6d:80:c4f1:32a:4521:c38'     => 'Something 4',
    '193.194.1.37'     => 'Something 5',

When I log in with a quite another ip (IPv4), then it shows up the description Something 1. After logging in for a second time with another ip it shows the description Something 1 as well.

Customers already asked me if I am spying on them because it always shows Something 1 logged in the last time.

**Comment by dsoares** [comment]
It was a bug, the plugin was not prepared to compare IPv6 addresses.
I added some support in [release 0.1.1](https://github.com/dsoares/Roundcube-Plugin-Geolocation/releases/tag/0.1.1), but it was only tested with internal IPv6 addresses.
