### ISSUE TITLE
Use Maxmind pure PHP API

### ISSUE THREAD

**Issue by dsoares** [dsoares/roundcube-geolocation#3]
Test the usage of the Maxmind pure PHP API (performance, IPv6 support, ...)

Links:
- [MaxMind GeoIP Legacy PHP API](https://github.com/maxmind/geoip-api-php)
- [GeoIP2 PHP API](https://github.com/maxmind/GeoIP2-php)

and 
- [MaxMind DB Reader PHP API](https://github.com/maxmind/MaxMind-DB-Reader-php)

> Optional PHP C Extension
> 
> MaxMind provides an optional C extension that is a drop-in replacement for for MaxMind\Db\Reader. In order to use this extension, you must install the Reader API as described above and install the extension as described below. If you are using an autoloader, no changes to your code should be necessary.

**Comment by mckaygerhard** [comment]
err a question.. this will affect php related, i mean, i need to install external dependencies .. jejej

i like to use the provides by current os vendor , by exmple the php-geoip provided by php api in debian stable...

at least if all needed depends (modified) will load with the plugin files!

**Comment by dsoares** [comment]
From what i've read, the PHP GeoIP extension is totally deprecated. Its last stable release is from 2011 and it does not support IPv6.
And the "external dependencies" would be easily solved with composer (there's a Maxmind package).

**Comment by mckaygerhard** [comment]
the problem its that in the production server there's a special patched php version 5.3.10 supported by the vendor provider that offers stability with security patches and more performance respect the recents versions... u'r plugin works great and its used in the main production server with an amount of 500~600 users concurrently..  we spected in one year 1000 users in, wheantime i cannot detail mor3e but in future of course we promote u'r efforces
