### ISSUE TITLE
please enable the wiki to i can documented

### ISSUE THREAD

**Issue by mckaygerhard** [dsoares/roundcube-geolocation#4]
hello @dsoares  this plugin repo does not have wiki module enable, but if u enalbe i can documented once u explainme how to use it!

i wish too this info how to use, due i reworked the converse.js plugin so..

as i suspech like you, you have used plugins in roundcube for intranet's right? me too need intranet capabilities, so in converse.js i have the idea to track the ip and location in resource identifier, using the provided functionallity by your plugin..

how can i use the ip and location provided by your plugin? in other plugin!? please take with patience, i'm not expert! unless u made it!

**Comment by dsoares** [comment]
I don't think it is necessary to enable the wiki. This is a very simple plugin, the README is sufficient to document it.
To use the information provided by this plugin in your code, see https://github.com/dsoares/Roundcube-Plugin-Geolocation/issues/1#issuecomment-228023098.
