### ISSUE TITLE
White page when activating last login and geolocalization

### ISSUE THREAD

**Issue by fabianbur** [dsoares/roundcube-geolocation#5]
White page when activating dsoares/lastlogin and roundcube-geolocation plugins
Roundcube 1.3.7

logs:
[15-Aug-2018 11:51:45 America/Guayaquil] PHP Fatal error:  Uncaught Error: Call to undefined function geoip_record_by_name() in /var/www/roundcube/plugins/geolocation/geolocation.php:119
Stack trace:
#0 /var/www/roundcube/plugins/geolocation/geolocation.php(67): geolocation::get_geolocation_info('xxxx:xxxx:xxxx:xxxx:x....', 'system')
#1 /var/www/roundcube/plugins/lastlogin/lastlogin.php(413): geolocation->get_geolocation('xxxx:xxxx:xxxx:xxxx:x...')
#2 /var/www/roundcube/plugins/lastlogin/lastlogin.php(135): lastlogin->get_geo('xxxx:xxxx:xxxx:xxxx:x....')
#3 /var/www/roundcube/plugins/lastlogin/lastlogin.php(74): lastlogin->save_info()
#4 /var/www/roundcube/program/lib/Roundcube/rcube_plugin_api.php(440): lastlogin->render_page(Array)
#5 /var/www/roundcube/program/include/rcmail_output_html.php(637): rcube_plugin_api->exec_hook('render_page', Array)
#6 /var/www/roundcube/program/include/rcmail_output_html.php(488): rcmail_output_html->parse('mail', false)
#7 /var/www/roundcube/index.php(316): rcmail_output_html->send('mail')
#8 {main}
  thrown in /var/www/roundcube/plugins/geolocation/geolocation.php on line 119

**Comment by dsoares** [comment]
`PHP Fatal error: Uncaught Error: Call to undefined function geoip_record_by_name()`

Seems like you did not install the required PHP GeoIP library (from PECL). 
Please, have a look at the Requirements section on the README page:

> **Requirements**
> [PHP GeoIP extension](https://php.net/manual/en/book.geoip.php) if using the `system` method to fetch geolocation information (recommended).

NOTE: i did not put it into the composer requirements because the other fetch methods do not require that library.

**Comment by fabianbur** [comment]
Thanks, using apt install php-geoip was solved. that extension is not required during the installation of roundcube, so it was not installed

Effectively in the page of the roundcube lastlogin plugin that requirement is not found https://plugins.roundcube.net/packages/dsoares/lastlogin yes in the page of the geoip plug-in. the one needs the other and through composer they are installed automatically. I suggest to put it also as a warning on the page of the pugin lastlogin. Thanks again.

Gracias, imediante apt install php-geoip se solucionó. esa extensión no es requisito durante la instalación de roundcube, por eso no estaba instalada

Efectivamente en la página del plugin lastlogin de roundcube no se encuentra ese requerimiento https://plugins.roundcube.net/packages/dsoares/lastlogin sí en la página del plugin geoip. el uno necesita el otro y mediante composer se instalan de forma automática. sugiero ponerlo también como advertencia en la página del pugin lastlogin. Gracias de nuevo.
