### ISSUE TITLE
installing plugin

### ISSUE THREAD

**Issue by Blisk** [dsoares/roundcube-geolocation#7]
I just copied folder into plugin folder and rename file to config.inc.php
but there is no settings in roundcube for geoip
I use roundcubemail 1.2.6.

**Comment by dsoares** [comment]
Hi,

The plugin does not have a graphical interface. As it is said in README, this plugin is not meant to be configured by users, only by the Roundcube Webmail administrator via the plugin configuration file.
Also, it is a support library for other plugins that need geolocation tools, this plugin doesn't do anything by itself.

If you plan to use other plugins that need geoip tools (like [blacklist plugin](https://github.com/dsoares/roundcube-blacklist) to block access by country), you need to have this plugin in `<roundcube_install_dir>/plugins/geolocation/`, copy `config.inc.php.dist` to `config.inc.php` and edit it accordingly to your system. Also, don't forget the Requirements and Configuration sections: if you configure to use the `system` fetch method, you need to have the [PHP GeoIP extension](https://php.net/manual/en/book.geoip.php) enabled in your PHP settings.
